const API_BASE_URL = 'https://rolling-api.vercel.app';

const MESSAGE_LIMIT_DEFAULT = 6;
const MESSAGE_OFFSET_DEFAULT = 0;

const MESSAGE_DELETE_STATUS = 204;

export {
  API_BASE_URL,
  MESSAGE_LIMIT_DEFAULT,
  MESSAGE_OFFSET_DEFAULT,
  MESSAGE_DELETE_STATUS,
};
